FROM tensorflow/tensorflow:1.5.1-devel-gpu-py3

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update
RUN apt-get install -y git && apt-get install -y make && apt-get install -y gcc && apt-get install -y g++
RUN apt-get install -y vim 

COPY tf_gpu_test.py /root

WORKDIR /root

RUN git clone https://github.com/danielgordon10/thor-iqa-cvpr-2018.git
RUN git clone https://github.com/pjreddie/darknet.git

WORKDIR /root/darknet
#RUN sed -i '/GPU=0/c\GPU=1' Makefile
#RUN ln -s /usr/local/cuda-9.0 /usr/local/cuda
RUN make


#WORKDIR /root/thor-iqa-cvpr-2018
#pip install --upgrade pip
#pip install -r requirements.txt
#sh download_weights.sh

WORKDIR /root

ENTRYPOINT ["python3", "tf_gpu_test.py"]
