#dockerfile for experimenting with tensorflow 1.5 code
FROM tensorflow/tensorflow:1.5.1-devel-gpu-py3

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && apt-get install -y vim

COPY tf_gpu_test.py /root

VOLUME "/data"

WORKDIR /root

ENTRYPOINT ["python3", "tf_gpu_test.py"]
